Define "errortitle" and "errordescr" params
simplesamlphp/simplesamlphp-module-authX509 pull request #4
Opened 2020-12-09 09:51 UTC by sprytnyserek

`simplesamlphp-module-authX509/templates/X509error.twig` contains references to *errortitle* and *errordescr* parameters. However they both are undefined. It should be in the method **authFailed** in: https://github.com/simplesamlphp/simplesamlphp-module-authX509/blob/3fcb6a060a1852495b4ec9ec740f623db8e0eba7/lib/Auth/Source/X509userCert.php#L87

This pull request addresses this issue by putting an error code and a corresponding error message if available.

2020-12-09 09:56 UTC, thijskh requested changes

2020-12-09 09:56 UTC, thijskh commented on lib/Auth/Source/X509userCert.php
> +        }
This is the result of refactoring towards twig templates that was incomplete. To fully clean it up I propose the following:
- Do not set `errorcode` and `errorcodes` as template variables but just as local variables and use those in the code in the added lines above.
- Change the `if` condition in the twig template to test for presence of `errordescr`.

2020-12-10 10:30 UTC, thijskh approved these changes

2020-12-10 10:30 UTC, thijskh commented
Thanks!

2020-12-10 10:30 UTC, merged

2020-12-10 12:09 UTC, tvdijen commented
Does this require backporting to the 0.9 branch?

2020-12-10 12:45 UTC, sprytnyserek commented
The problem exists in 0.9.

Btw. I've just realized my fault in loading error info. Instead of this:
```
$t->data['errortitle'] = $errorcode;
        if (array_key_exists($errorcode, $errorcodes)) {
            $t->data['errordescr'] = $errorcodes[$errorcode];
        } else {
            $t->data['errordescr'] = $errorcode;
        }
```
I should do something like this (+ null checks etc.):
```
$t->data['errortitle'] = $errorcodes['title'][$errorcode];
        if (array_key_exists($errorcode, $errorcodes['descr'])) {
            $t->data['errordescr'] = $errorcodes['descr'][$errorcode];
        } else {
            $t->data['errordescr'] = $t->data['errortitle'];
        }
```
I'll fix it soon.

2020-12-10 17:42 UTC, thijskh commented
In 0.9 the problem exists only in the new templates (not used by default so probably  therefore not detected). Fix for 0.9 will need to consider to keep old templates working aswell.

2020-12-10 19:08 UTC, tvdijen commented
Ack, will wait for the final fix and then port it to 0.9